root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "cd ./resources && npx tailwindcss -i src/styles.css -o ../public/css/styles.css && cd ../ && templ generate && go build -o ./tmp/main ."
  delay = 200
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

  
  
[watcher]
full = true
dirs = ["./resources", "./routes", "./views"] # Add all necessary directories here

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false